name: Testing Schedule CI

on:
    schedule:
        - cron: '0 0 * * *'
env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        coverage run manage.py test housing
    - name: Generate Test Coverage
      run: |
        coverage report
        coverage json
    - name: Generate HTML Pages for Test COverage
      run: |
        coverage html
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./htmlcov/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        files: ./coverage.json
        flags: unittests
        name: codecov-umbrella
        verbose: true
