# Generated by Django 4.1.1 on 2022-12-02 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0004_merge_20221009_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.owner'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='associated_apt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing.apartment'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='lease_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='housing.lease'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
