# Generated by Django 4.1.1 on 2022-12-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0005_alter_apartment_owner_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='id',
            field=models.BigAutoField(auto_created=True,
                                      primary_key=True,
                                      serialize=False,
                                      verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='id',
            field=models.BigAutoField(auto_created=True,
                                      primary_key=True,
                                      serialize=False,
                                      verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='id',
            field=models.BigAutoField(auto_created=True,
                                      primary_key=True,
                                      serialize=False,
                                      verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True,
                                      primary_key=True,
                                      serialize=False,
                                      verbose_name='ID'),
        ),
    ]
