# Generated by Django 5.1.2 on 2024-10-31 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing',
         '0006_alter_apartment_id_alter_flat_id_alter_lease_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('preference_type', models.CharField(max_length=20,
                                                     unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_preferences',
            field=models.ManyToManyField(blank=True,
                                         to='housing.userpreference'),
        ),
    ]
