# Generated by Django 5.1.2 on 2024-11-27 02:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing', '0007_userpreference_user_user_preferences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review', models.CharField(max_length=500)),
                ('apartment_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='housing.apartment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='housing.user')),
            ],
        ),
    ]
